on:
  push:
    branches:
      - master
      - develop
      - psa
  pull_request:

name: CI
jobs:
  phpunit:
    runs-on: ubuntu-20.04

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: secret
          MYSQL_DATABASE: evidentia
          MYSQL_USER: evidentia
          MYSQL_PASSWORD: secret
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Verify MySQL connection from host
        run: |
          sudo apt-get update && sudo apt-get dist-upgrade && sudo apt-get install mysql-server
          mysql --host 127.0.0.1 --port 3306 -uroot -psecret -e "GRANT ALL ON *.*  TO 'evidentia'@'%' identified by 'secret'; FLUSH PRIVILEGES;"
          mysql --host 127.0.0.1 --port 3306 -uroot -psecret -e "CREATE DATABASE base21;"
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: Install composer dependencies
        run: |
          rm composer.lock
          composer install --no-scripts
          composer update

      - name: Prepare Laravel Application
        run: |
          cp .env.ci .env
          php artisan migrate
          php artisan db:seed
          php artisan db:seed --class=InstancesTableSeeder
          php artisan migrate --path=database/migrations/develop
          php artisan db:seed --class=DevelopSeeder
      - name: Run Testsuite
        run: vendor/bin/phpunit tests/

  deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Stage
        uses: actions/checkout@v1
        with:
          url: 'https://www.evidentia.cloud/deploy'
          method: 'POST'
          username: ${{ secrets.EVIDENTIA_DEPLOY_USER }}
          password: ${{ secrets.EVIDENTIA_DEPLOY_PASSWORD }}
